Repository MokshaDill/Donner-ConnectX, pull requests merged in 2024-09, with the labels that each got.

#13 Frontend Integration
  Donner-Connect/.idea/compiler.xml
Labels: enhancement

#16 Feature/contributor servive
  Donner-Connect/ContributorService/src/main/java/com/springbootcrud/contributorservice/controller/ContributorController.java
  Donner-Connect/ContributorService/src/main/resources/application.properties
  Front-End_Donner_Connect/Contributor/index.html
Labels: enhancement

#19 Feature/campmgt service
  Donner-Connect/CampMGTService/src/main/java/com/springbootcrud/campmgtservice/controller/CampController.java
  Donner-Connect/CampMGTService/src/main/java/com/springbootcrud/campmgtservice/entity/Camp.java
  Donner-Connect/CampMGTService/src/main/resources/application.properties
  Front-End_Donner_Connect/Camp/js/camp.js
Labels: enhancement, help wanted

#22 Feature/auth service
  Donner-Connect/AdminService/src/main/resources/application.properties
  Donner-Connect/AuthenticationService/pom.xml
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/config/AppConfig.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/config/SecurityConfig.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/config/WebConfig.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/config/filter/JwtAuthenticationFilter.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/controller/AuthenticationController.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/entity/AuthenticationResponse.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/entity/Contributor.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/entity/Role.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/entity/User.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/model/AuthenticationResponse.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/model/Role.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/repository/ContributorRepository.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/repository/UserRepository.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/services/AuthenticationService.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/services/ContributorService.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/services/JwtService.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/services/impl/AuthenticationServiceImpl.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/services/impl/ContributorServiceImpl.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/services/impl/JwtServiceImpl.java
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/services/impl/UserDetailsServiceImp.java
  Donner-Connect/AuthenticationService/src/main/resources/application.properties
  Donner-Connect/FeedbackService/pom.xml
  Donner-Connect/FeedbackService/src/main/java/com/springbootcrud/analysisservice/AnalysisServiceApplication.java
  Donner-Connect/FeedbackService/src/main/resources/application.properties
  Donner-Connect/FeedbackService/src/test/java/com/springbootcrud/analysisservice/AnalysisServiceApplicationTests.java
  Front-End_Donner_Connect/Admin/Capture.PNG
  Front-End_Donner_Connect/Admin/index.html
  Front-End_Donner_Connect/Admin/main.js
  Front-End_Donner_Connect/Admin/style.css
  Front-End_Donner_Connect/login/contributor/contributor_login.html
  Front-End_Donner_Connect/login/contributor/login.css
  Front-End_Donner_Connect/login/contributor/login.js
  Front-End_Donner_Connect/login/login.html
  Front-End_Donner_Connect/login/register.html
  Front-End_Donner_Connect/login/scripts.js
  Front-End_Donner_Connect/login/styles.css
Labels: bug

#23 Feature/campmgt service
  Donner-Connect/CampMGTService/src/main/java/com/springbootcrud/campmgtservice/controller/CampController.java
  Donner-Connect/CampMGTService/src/main/java/com/springbootcrud/campmgtservice/service/CampService.java
  Donner-Connect/CampMGTService/src/main/java/com/springbootcrud/campmgtservice/service/impl/CampServiceImpl.java
  Front-End_Donner_Connect/Camp/js/camp.js
Labels: enhancement

#24 Feature/campmgt service
  Donner-Connect/AuthenticationService/src/main/java/com/springbootcrud/authenticationservice/config/WebConfig.java
  Front-End_Donner_Connect/Camp/js/camp.js
  Front-End_Donner_Connect/login/contributor_login/.vscode/settings.json
  Front-End_Donner_Connect/login/contributor_login/index.html
  Front-End_Donner_Connect/login/contributor_login/login.css
  Front-End_Donner_Connect/login/contributor_login/login.js
Labels: enhancement
